### ISSUE TITLE
Incorrect dimensions: output = torch.matmul(A_hat, output) 

### ISSUE THREAD

**Issue by orangchen1998** [vinhsuhi/EMGCN#3]
When i resume your work, i found A_hat is 38776X38776, output is 19388X300.  I want to confirm with you whether source_feats and the target_feats  in the data set is correct. Why have this problem? Looking forward to your reply. Thank you!

**Comment by orangchen1998** [comment]
I have this question.
> 
`Traceback (most recent call last):
  File "network_alignment.py", line 106, in <module>
    S = model.align()
  File "/home/test/Documents/model_EA/used_project/EMGCN/algorithms/EMGCN/EMGCN.py", line 284, in align
    self.train_embedding(embedding_model, refinement_model, source_A_hat, target_A_hat, structural_optimizer, source_A_hat_sym, target_A_hat_sym)
  File "/home/test/Documents/model_EA/used_project/EMGCN/algorithms/EMGCN/EMGCN.py", line 240, in train_embedding
    outputs = embedding_model(source_A_hat, 's')[1:]
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/test/Documents/model_EA/used_project/EMGCN/algorithms/EMGCN/embedding_model.py", line 132, in forward
    return self.forward_undirect(A_hat, emb_input)
  File "/home/test/Documents/model_EA/used_project/EMGCN/algorithms/EMGCN/embedding_model.py", line 111, in forward_undirect
    GCN_output = self.GCNs[i](A_hat, emb_input)
  File "/home/test/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/test/Documents/model_EA/used_project/EMGCN/algorithms/EMGCN/embedding_model.py", line 39, in forward
    output = torch.matmul(A_hat, output)
RuntimeError: addmm: Argument #3 (dense): Expected dim 0 size 38776, got 19388`

**Comment by orangchen1998** [comment]
Why is the size of the source data you provided is inconsistent? I just read the data without any other processing. Therefore, the reason for my operation error can be ruled out. This is a screenshot of the evidence.
![image](https://user-images.githubusercontent.com/50953433/145678867-efa315ca-15bc-45b9-b0c5-09ba211a8c04.png)
![image](https://user-images.githubusercontent.com/50953433/145678872-5aa6c562-8489-44f0-a75f-f82d1fcf176a.png)

**Comment by lilychou0912** [comment]
@orangchen1998 想知道是怎么解决这个问题的呢？我也遇到了，谢谢！

**Comment by 1453287898** [comment]
Can I ask you the source dataset? The link which author provided is lose.

**Comment by 1453287898** [comment]
> When i resume your work, i found A_hat is 38776X38776, output is 19388X300. I want to confirm with you whether source_feats and the target_feats in the data set is correct. Why have this problem? Looking forward to your reply. Thank you!

Can I ask you the source dataset? The link which author provided is lose.Thank you so much
